/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef chord_dht_CONSTANTS_H
#define chord_dht_CONSTANTS_H

#include "chord_dht_types.h"



class chord_dhtConstants {
 public:
  chord_dhtConstants();

};

extern const chord_dhtConstants g_chord_dht_constants;



#endif
