/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "chord_join_remove_dht_constants.h"



const chord_join_remove_dhtConstants g_chord_join_remove_dht_constants;

chord_join_remove_dhtConstants::chord_join_remove_dhtConstants() {
}



