/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef chord_join_remove_dht_CONSTANTS_H
#define chord_join_remove_dht_CONSTANTS_H

#include "chord_join_remove_dht_types.h"



class chord_join_remove_dhtConstants {
 public:
  chord_join_remove_dhtConstants();

};

extern const chord_join_remove_dhtConstants g_chord_join_remove_dht_constants;



#endif
