/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef stable_chord_CONSTANTS_H
#define stable_chord_CONSTANTS_H

#include "stable_chord_types.h"



class stable_chordConstants {
 public:
  stable_chordConstants();

};

extern const stable_chordConstants g_stable_chord_constants;



#endif
