/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "stable_chord_constants.h"



const stable_chordConstants g_stable_chord_constants;

stable_chordConstants::stable_chordConstants() {
}



